all:
	make -C xlib all
	make -C libm all
	make -C libc all
	make -C kl   all
	make -C examples all

install:
	make -C xlib install
	make -C libm install
	make -C libc install
	make -C kl   install
	make -C examples all

clean:
	make -C xlib clean
	make -C libm clean
	make -C libc clean
	make -C kl   clean
	make -C examples clean
